stages:
  - build-docker
  
variables:
  IMAGE_VERSION: $CI_BUILD_TAG

build-docker:
  stage: build-docker
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_BUILD_TAG
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags
